services:
  db:
    container_name: postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: sol
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  sol-api:
    container_name: sol-api
    image: solenja/sol-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  sol-react:
    container_name: sol-react
    image: solenja/sol-react
    build:
      context: frontend/react
      args:
        api_base_url: http://sol-api-env.eba-fjgs4ydm.eu-north-1.elasticbeanstalk.com:8
    ports:
      - "3003:5173"
    depends_on:
      - sol-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:

